### ISSUE TITLE
What section covers CD on spell procs on items with equip: effect?

### ISSUE THREAD

**Issue by Sulan2** [stoneharry/Spell-Editor-GUI-V2#149]
If we take for example this item 
https://wotlkdb.com/?item=12641

it says there is a 30s window in which it cannot proc but when I look up the spell it procs with the spell editor program 16620 and 16621 there is nothing that says there would be a 30s CD on it
However in game there is a 30s CD on it and online database also says it has a 30s CD

Do u have any idea what modifies this in the Spell editor program?

**Comment by stoneharry** [comment]
Happy to help, it's taken me years to learn all this stuff. There's a hundred ways I could improve the spell editor to make editing this sort of thing easier, but it all takes time which I don't have much of these days. 😄

I'll close this issue, please feel free to open a new one if you have another question.
