### ISSUE TITLE
Unable to load spell

### ISSUE THREAD

**Issue by Persephone** [stoneharry/Spell-Editor-GUI-V2#16]
For some reason loading spell:

holy shield - ID: 48952

It just wont, it is stuck at this forever: http://puu.sh/jRoUX/f9f7d39bc0.png

I recently updated today, my last version was months old, where it would load it but it would show no stats and no information at all, like it was loading wrong. Not sure what is causing it.

**Comment by stoneharry** [comment]
Will look at it when I get a chance. Can you test if other spells are loading fine?

**Comment by Persephone** [comment]
Other spells load fine, this happends to a few spells.

Also had issues saving to mysql using it, it happened a few times.

**Comment by stoneharry** [comment]
I want to look at this but I just haven't had any free time recently.

**Comment by Dokman** [comment]
here is the bug
![image](https://cloud.githubusercontent.com/assets/2290904/14802648/d37554f4-0b52-11e6-9ac7-cb0e8b00f656.png)

**Comment by Dokman** [comment]
any updates to this?

**Comment by stoneharry** [comment]
I'll hopefully take a look at the weekend.

**Comment by Dokman** [comment]
thansk :crescent_moon:

**Comment by stoneharry** [comment]
Should be fixed in https://github.com/stoneharry/Spell-Editor-GUI-V2/releases/tag/v1.4.6. Let me know.
