### ISSUE TITLE
Spell save doesnt work

### ISSUE THREAD

**Issue by Athris** [stoneharry/Spell-Editor-GUI-V2#22]
I update the 1.4.5 version to the new 1.4.6 version. Now i modify a spell and click on "Save spell change" button. If i reload the modify spell then my changes are lost. Version 1.4.5 working.

**Comment by stoneharry** [comment]
This should be fixed in the new version. Please test and let me know: https://github.com/stoneharry/Spell-Editor-GUI-V2/releases/tag/v1.4.7

**Comment by Athris** [comment]
You fixed it. Thank you.
