### ISSUE TITLE
Stuck (looping) on loading spells & creature type corrupts

### ISSUE THREAD

**Issue by takezandgoez** [stoneharry/Spell-Editor-GUI-V2#24]
Release Build 1.4.8:

Polymorph (Corrupts Target [Creature Types] in MISC & marks as giants) must re-enter flags then save
Health Funnel (Stuck on opening spell wont load & stuck in loop) must force close [x]
Life Tap (Stuck on opening spell wont load & stuck in loop) must force close [x]
Bloodrage (Stuck on opening spell wont load & stuck in loop) must force close [x]
Probably more with same issue, these spells load in some older versions.

Saving stacks up & becomes slower after each save.

**Comment by stoneharry** [comment]
Please provide the exact spell ID's that you are trying to edit.

**Comment by takezandgoez** [comment]
Here's my answer that you give to everyone else.

I got you half way there now figure the rest out by yourself. 

P.S. Go fuck yourself
....................../´¯/) 
....................,/¯../ 
.................../..../ 
............./´¯/'...'/´¯¯`·¸ 
........../'/.../..../......./¨¯\ 
........('(...´...´.... ¯~/'...') 
.........\.................'...../ 
..........''...\.......... _.·´ 
............\..............( 
..............\.............\...

**Comment by stoneharry** [comment]
Not a valid bug report.
