### ISSUE TITLE
SpellVisualMapBuilder database structure is deprecated

### ISSUE THREAD

**Issue by Archimoon** [stoneharry/Spell-Editor-GUI-V2#29]
The structure of the CreatureTemplate.sql in SpellVisualMapBuilder/Export doesn't work with the TrinityCore Database 2016 - 10 - 17

When I run SpellVisualMapBuilder.exe there is no new file generated...

**Comment by stoneharry** [comment]
It was written quickly for my version of TrinityCore, you will have to adjust the output to match the structure in your version of the database.

Here is where you need to modify it: https://github.com/stoneharry/Spell-Editor-GUI-V2/blob/master/SpellVisualMapBuilder/Program.cs#L125

You can read the output of the program by running it from command prompt.
