### ISSUE TITLE
Go to Spell

### ISSUE THREAD

**Issue by Lawys** [stoneharry/Spell-Editor-GUI-V2#30]
![8c793121da1a5d4458e388f7c0b805e5](https://cloud.githubusercontent.com/assets/5355630/20061826/c2155ae4-a501-11e6-912b-5c93a2e8769c.gif)

I compiled ur latest version

what is the problem ?

**Comment by m-uu** [comment]
I have fixed the problem.

modify SpellGUIV2/MainWindow.xaml.cs

```
                    for (int i = 0; i < SelectSpell.Items.Count; ++i)
                    {
                        string item = SelectSpell.Items.GetItemAt(i).ToString();

                        if (Int32.Parse(item.Split(' ')[0]) == ID)
                        {
                            SelectSpell.SelectedIndex = i;
                            SelectSpell.ScrollIntoView(SelectSpell.Items.GetItemAt(i));

                            break;
                        }
                    }
```

to

```
					Int32 count = 0;
					foreach (StackPanel obj in SelectSpell.Items)
					{
						foreach (var item in obj.Children)
							if (item is TextBlock)
							{
								TextBlock tb = (TextBlock)item;

								if (Int32.Parse(tb.Text.Split(' ')[1]) == ID)
								{
									SelectSpell.SelectedIndex = count;
									SelectSpell.ScrollIntoView(obj);

									break;
								}
							}
						count++;
					}
```

**Comment by Lawys** [comment]
Dont works

**Comment by m-uu** [comment]
![untitled3](https://cloud.githubusercontent.com/assets/5546244/20063172/26886496-a541-11e6-915f-1c6b985de610.gif)

No problem

**Comment by Lawys** [comment]
I have the latest version. (u?) You dont forgot something in the code to modify ?

(How can u create a gif longer than 7 seconds ?)

**Comment by m-uu** [comment]
I use the version is 1.4.9. And i haven't other changes.
Use some tools.

(now in china is 23:50.so,i must go to bed.seeyou.)

**Comment by Lawys** [comment]
Ok solved, thx full :)

**Comment by stoneharry** [comment]
@m-uu Thanks!

I will integrate this into the code at some point.

**Comment by m-uu** [comment]
No thanks, I like the program very much, and I pushed my changes to my github.
Fixed some minor problems.
@stoneharry

**Comment by stoneharry** [comment]
Merged changes from @m-uu finally. Added a new release to use these changes. Issue can be closed now. 👍
