### ISSUE TITLE
Bug, missing or just mybad ?

### ISSUE THREAD

**Issue by Lawys** [stoneharry/Spell-Editor-GUI-V2#31]
example : spell 20597,

ingame : requires sword, 2h sword

on myspelleditor : nothing about that

**Comment by m-uu** [comment]
Just because there's no processing.

**Comment by Lawys** [comment]
70	int32	EquippedItemSubClassMask

**Comment by m-uu** [comment]
The editor does not handle this parameter.
Requires the author or you or I or anyone else in the code to add this parameter to the processing. :P

**Comment by m-uu** [comment]
@stoneharry This needs to be converted to a binary representation.
Used to identify the necessary equipment. And i have finished processing this part.
I pushed those changes to GitHub yesterday.
Been busy with work before, forget to push to GitHub.

**Comment by stoneharry** [comment]
Awesome, just merged it now @m-uu ! 👍 

@Lawys try v1.5.1.
