### ISSUE TITLE
I am trying to modify MySQL for sqlite. I need help

### ISSUE THREAD

**Issue by m-uu** [stoneharry/Spell-Editor-GUI-V2#33]
hello. @stoneharry.
Because of the use of the editor to open an MySQL service, there is a little inconvenient.
so I am trying to modify the MySQL sqlite. to make the program does not need to rely on the MySQL can work normally. The current editor has been able to read the spelldbc data to the database. 
Can generate  tables.
Editor can also browse spell information. 
However,when the output of spell.dbc there are some mistakes I couldn't resolve. 
And SpellDescriptionGen will go wrong (I temporary note the SpellDescriptionGen) 
And some unexpected mistakes. 
I want to know if you think SQLite is a feasible change? If possible, I hope to get your help. Thank you.
I have to change my push to my github. if you have the time I hope you can help look now.

  I hope you can understand what I said above.I will try my best to improve my English. - -!

**Comment by stoneharry** [comment]
Mmmm. SQLite should be feasible, but we should make it configurable whether it uses mysql or SQLite rather than hardcoding it one way or the other.


I will look at it when I get time. Merry Christmas!

**Comment by stoneharry** [comment]
I just had a quick look at this. I started by converting SQLite and MySQL to be based off a new interface: DBAdapter. This means that we can construct either one based on some configurable option and pass the same variable around.

At the moment it is hardcoded to be MySQL. The next stage will be to make it configurable and look at the bugs you mentioned. I am undecided on how to improve the configuration - MahApps doesn't actually even support password fields by default. I can implement a custom one, but even more time for something I don't have much time to work on.

Anyway, I have checked the progress thus far into my master branch: https://github.com/stoneharry/Spell-Editor-GUI-V2/commits/master

**Comment by m-uu** [comment]
Merry Christmas to you, too.
Because I have to pay attention to your git dynamic. 
So guess you normally is a little bit busy. Very thank you for taking the time to!
I will do my best to try to modify, try not to spend too much of your time. Thank you again for your work.
I want to do a multilingual, add a tooltip for a variety of parameters(Currently has completed several parameters of the tooltip), the database to keep a text description of each parameter (or tooltip), the user can change in the database (mysql or sqlite) text description (such as a tooltip text), rather than hardcoding source code.
Before that, I have put the tool in English translated into Chinese, but need a lot of changes to the source code. So the idea, the text description saved to the database (similar to the trinitycore table trinity_string).
This may require more than one table to store the data. 
So I have a idea, use sqlite to create this tool dedicated database (a lightweight, portable).
The end of the year, work a little busy, if possible I will try to take time to complete the idea. Programming level is not very good, may I have a lot of places need to give directions.

**Comment by stoneharry** [comment]
I have created a new branch to track my changes on this:

https://github.com/stoneharry/Spell-Editor-GUI-V2/tree/SQLite

Once SQLite is working and you can choose whether to use MySQL or SQLite based on a config option I will merge it back into master. 👍 I will keep working on it as I have free time.

**Comment by stoneharry** [comment]
I've now done the configuration aspect and fixed some bugs.

While I was messing around with stuff I also fixed up the icon editor a lot and implemented a slider to resize the icons.

The editor seems to work fully with SQLite mode but I haven't tested the spell.dbc's it produces in game yet. I am not sure when I will have a chance to do this. I will test as soon as I can.

**Comment by stoneharry** [comment]
I actually just pushed a new release, v1.6, with all of the stuff from the SQLite branch merged in. I think it's in a testable state.

**Comment by m-uu** [comment]
This is a good news. Before that, I have already tested editor sqlite mode basically can work properly. There may be some small problems need to be repaired.
When I have time, I will gradually transfer some text description to the database.

**Comment by stoneharry** [comment]
Since SQLite is in now and working pretty good I'm going to close this ticket. We can use #35 to track the localisation of the interface.
