### ISSUE TITLE
Spell editor specified cast is not valid

### ISSUE THREAD

**Issue by robbie5325** [stoneharry/Spell-Editor-GUI-V2#34]
I think that this is something on my end, can anyone please confirm or tell me if there's an easy fix?

**Comment by stoneharry** [comment]
Screenshot, version, and language please.

**Comment by Alexstraza** [comment]
![yeah](https://cloud.githubusercontent.com/assets/14054074/21473608/cf8f99ce-cb11-11e6-802b-9d2f16d19ac3.PNG)

Same issue here while trying to edit Battle Stance.

**Comment by robbie5325** [comment]
Sorry for late reply, the screenshot is the same as his, it doesn't matter the actual cast time of the spell, either, because it's apparently a sql error.
Version is latest, I tried the last two releases and neither one worked, same error.

**Comment by stoneharry** [comment]
What is it you are doing when you get this error message? What spell Id are you loading? Will take a look at it after Christmas. Merry Christmas!

**Comment by robbie5325** [comment]
Merry Christmas!
Any spell that I edit does it, actually.
I tried on a whole bunch of them and it gives this error.

**Comment by stoneharry** [comment]
Fixed in ed1f9302aa94a78e32b29e51ef75af4418dd6467. I will close this ticket once the next release is made.

**Comment by robbie5325** [comment]
Awesome, keep up the good work!
Any eta on next release?

**Comment by stoneharry** [comment]
Posted the new release - v1.5.2.
