### ISSUE TITLE
Import Spell.DBC even though table is full

### ISSUE THREAD

**Issue by tikki100** [stoneharry/Spell-Editor-GUI-V2#38]
The spell editor allows you to click "Import Spell.dbc to MySQL" even though the table in the database is not empty.

It will show a message, stating that the table appears empty, asking the user whether they wish to fill it or not. Clicking continue will result in a mySQL error, leaving the user clueless that they have to truncate the table first.

**Comment by m-uu** [comment]
We can disable the button when database table is not empty.
