### ISSUE TITLE
Latest version BUG SQlite

### ISSUE THREAD

**Issue by syphex97** [stoneharry/Spell-Editor-GUI-V2#39]
so i tried using the latest version, seems when you are in game it will use the valus on the tooltips that you use in the editor.

Lets say i want the paladin talent Hammer of justice, instead of saying it will decrease the cooldown with 10 seconds it will say 10000 seconds. While it decreases the cooldown by 10 seconds.

Lets say we have the Talent Improved Righteous Fury (Paladin talent, which is the one above too)
it will say 

"While Righteous Fury is active, all damage taken is reduced by 2/%" 
while it should say 
"While Righteous Fury is active, all damage taken is reduced by 2%" 

And it does this to all talents, seals etc. 

Everything that uses a value or % in stat increase or damage.

Like for Seal of Righteousness it will say

"Fills the paladin with holy spirit for 30 min, granting each meele attack $ additional Holy damage. Only one Seal can be active on the paladin at once.

Unleashing this  Seal's Energy will cause 2652 Holy damage to an enemy.
"
Now the problem with that is that it should give you a number instead of a symbol "$"

and so on, you get it.

**Comment by m-uu** [comment]
are you use the version is 1.6?

**Comment by syphex97** [comment]
Obviously i do since this is a problem with SQLIte

And the latest version is the only thing that supports SQLite.

As i still have an issue using the Mysql version.

**Comment by m-uu** [comment]
About the redundant "/" symbol, I have submitted my repair to the merged and main branch. Will be in a future version of fix this problem.
[75b607a](https://github.com/stoneharry/Spell-Editor-GUI-V2/commit/75b607aa2dd16e40f1a8fd9d4dea7d51a58cc354)

**Comment by syphex97** [comment]
Okay just tried out a few stuff, went forth and back, this happens with all versions from like 1.5+

both mysql and SQlite

No idea why it does this. It adds the "/" once you import the spell.dbc

**Comment by stoneharry** [comment]
This is a pretty program-breaking bug so I'll try to get round to this as soon as I can.

**Comment by syphex97** [comment]
I  noticed one thing, forgot to reply, my bad and that is that this started to happen after you added language support for like Chinese i think it was or something like that.

I think thats one thing that stuck out quite alot in one of the updates you made in one of the releases.

**Comment by stoneharry** [comment]
This should be fixed now. Please re-open the issue if you encounter it again.
