### ISSUE TITLE
Crash when selecting a spell and clicking on Icons button

### ISSUE THREAD

**Issue by komyg** [stoneharry/Spell-Editor-GUI-V2#41]
Hi,

I am using your software with the TrinityCore 3.3.5a and I am having some problems with the spell icons. I was able to successfully load the spell.dbc database into the SQL Lite, however whenever I select a spell and click on the "Icon" button of the interface, I get an unhandled exception saying this: "File could not be found: Icons\\Interface\\Icons\\Spell_Frost_IceStorm.blp"

The call stack is below:

```
SpellEditor.exe!SpellEditor.MainWindow.HandleErrorMessage(string msg) Line 133	C#
SpellEditor.exe!SpellEditor.Sources.DBC.SpellIconDBC.UpdateMainWindowIcons(double margin) Line 148	C#
SpellEditor.exe!SpellEditor.Sources.DBC.SpellIconDBC.LoadImages.AnonymousMethod__0() Line 91	C#
```

I've checked the folder from which I am running the program and it doesn't have an Icons\Inteface folder. I am not sure how to get it or generate it. Could you help me?

**Comment by stoneharry** [comment]
You need to extract them from the client. The release for this comes with the base images. I will make the error less obtrusive but it's not really an issue.

**Comment by komyg** [comment]
Hi, 

Thanks for the answer. I extrated the tbd files from the client using the TrinityCore extractor, but the images are not on the extracted files. Would you recommend using another extractor, like the one from Mangos?

**Comment by stoneharry** [comment]
http://www.zezula.net/en/mpq/download.html

You can open multiple MPQ's at once in merged mode, then you'll see the file paths it is talking about.

**Comment by stoneharry** [comment]
The releases can be found here: https://github.com/stoneharry/Spell-Editor-GUI-V2/releases

If you are running the program from your IDE (i.e: Visual Studio) then you will need to move the depend files to where the file is built and run from.
