### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by reidospalas** [stoneharry/Spell-Editor-GUI-V2#47]
If i try open my custom icons it load like 90% and crash!

**Comment by stoneharry** [comment]
It is a bug I am aware of affecting some people. I have not worked on this project for a while so I am not making any promises but I might have a look at this some time soon.

**Comment by m-uu** [comment]
The problem has been fixe in #48 and looks forward to the release of @stoneharry 's new release.

**Comment by stoneharry** [comment]
Added a new release so closing this ticket. 👍
