### ISSUE TITLE
Spell editor crashing on launch (clicking on MySQL)

### ISSUE THREAD

**Issue by Zentarg** [stoneharry/Spell-Editor-GUI-V2#49]
I'm using 64bit version of Window 10. The program (Latest Release) shuts down, after choosing to connect to a MySQL server (I have already set up the connection). The table has already been set up by the program, as I can see in my db, however the program just crashes quickly afterwards.

The occurance can be seen in this gif: https://gyazo.com/7e2eec286d5589f7b8c752ab832ed5ba

**Comment by Zentarg** [comment]
Figured out that I hadn't done as the ReadMe told me to do.. My bad. It stopped 'not working' when I replaced all the files in 32bit with the files in 34bit.

**Comment by stoneharry** [comment]
Awesome, glad you got it working. I released 64 and 32 (x86) bit versions of the program because it depends on your system which you need.
