### ISSUE TITLE
Am i able to update SpellEditor to 7.3.5?

### ISSUE THREAD

**Issue by Fingrebrigt** [stoneharry/Spell-Editor-GUI-V2#52]
If it's possible to update it, how can i do it?

**Comment by Grimton1337** [comment]
When you go to the front page, it says that it's only for Version 3.3.5, Build 12340. This will not work on any other client, as most of the structures are changed after each expansion, in addition to that, but unfortunately, the Spell structure is the most changed one over the years.

**Comment by stoneharry** [comment]
Well summed up, @Grimton1337 . Thanks.

The implementation needs to be changed to be able to read DB2 files as well as the changed structs in different patches.

Furthermore there is no UI dynamic builder parsing the data loaded and constructing elements on the fly. I experimented with this idea but it would be -a lot- of work. So you will need to go through and update the UI for all the different data loaded.

Closing this issue as the question is answered.
