### ISSUE TITLE
value was either too large or too small for an int32

### ISSUE THREAD

**Issue by robbie5325** [stoneharry/Spell-Editor-GUI-V2#53]
when attempting to edit spell 325 (lightning shield) and some others, it gives this error using sqlite AND mysql on the latest release.

**Comment by stoneharry** [comment]
I am not able to reproduce this using the latest version at this time: v1.7.1.

![Spell 325 selected](https://i.imgur.com/KIVbw9Q.png)
![Spell 325 base](https://i.imgur.com/yziUGV0.png)
![Spell 325 effects](https://i.imgur.com/eehSiGk.png)
![Spell 325 attributes](https://i.imgur.com/LJjC8Q2.png)

Are you using the latest version?

**Comment by stoneharry** [comment]
Closing issue, feel free to reopen if you are using the latest version and can reproduce this issue.

**Comment by robbie5325** [comment]
Occurs on any spell when its duration index is changed to "21"

**Comment by stoneharry** [comment]
> Occurs on any spell when its duration index is changed to "21" (infinite)

Reopened this issue, not tested this yet. Probably wont get a chance to look at it for a while, going on holiday tonight.

**Comment by stoneharry** [comment]
I'm not able to reproduce this using v1.8.1:

![img1](https://i.imgur.com/jH50WNk.png)
![img2](https://i.imgur.com/MI4gqH1.png)

**Comment by robbie5325** [comment]
confirmed, fixed in v1.8.1

**Comment by robbie5325** [comment]
confirmed, fixed in v1.8.1
