### ISSUE TITLE
Messages when completing an action

### ISSUE THREAD

**Issue by mmlTools** [stoneharry/Spell-Editor-GUI-V2#61]
Would be nice to have a success/error message after saving a spell something similar to the one you receive once a new spell is created. Sometimes I have to manually check in DB or refresh the program to make sure that changes were saved.

**Comment by stoneharry** [comment]
A good idea. We used to have one but it irritated me because you had to dismiss the notification. I'll try to make a more subtle way of displaying a confirmation.

**Comment by stoneharry** [comment]
How about this? 😁 

![Flyout panel for saving spell notification](https://i.imgur.com/QDVtrGB.png)

**Comment by stoneharry** [comment]
Added in fabead245142beb6222539de255f53920653d358.

**Comment by stoneharry** [comment]
This is fixed in release build v1.8.2 - closing this issue.
